@startuml 03-connector-types

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

title <b>Peer-to-Peer Connector Types</b>\nCommunication patterns between peers

package "Call-Return" as CR {
  rectangle "Peer A" as cr_a <<peer>>
  rectangle "Peer B" as cr_b <<peer>>
  cr_a -[$line_primary,bold]-> cr_b : " request "
  cr_b -[$line_primary,dashed]-> cr_a : " response "
}

package "Async Message" as AM {
  rectangle "Peer C" as am_c <<peer>>
  rectangle "Peer D" as am_d <<peer>>
  am_c -[$line_caution,bold]-> am_d : " fire & forget "
}

package "Stream" as ST {
  rectangle "Peer E" as st_e <<peer>>
  rectangle "Peer F" as st_f <<peer>>
  st_e =[$deep_alt,bold]=> st_f : " continuous data flow "
}

package "Multicast" as MC {
  rectangle "Peer G" as mc_g <<peer>>
  rectangle "Peer H" as mc_h <<peer>>
  rectangle "Peer I" as mc_i <<peer>>
  rectangle "Peer J" as mc_j <<peer>>
  mc_g -[$line_invalid,bold]-> mc_h : " broadcast "
  mc_g -[$line_invalid,bold]-> mc_i : " broadcast "
  mc_g -[$line_invalid,bold]-> mc_j : " broadcast "
}

legend right
  |<$line_primary> <color:$line_neutral>  Call-Return  </color>| Request/response |
  |<$line_caution> <color:$line_neutral>  Message  </color>| Asynchronous, no reply |
  |<$deep_alt> <color:$line_neutral>  Stream  </color>| Long-lived data flow |
  |<$line_invalid> <color:$line_neutral>  Multicast  </color>| One-to-many delivery |
end legend
@enduml
