@startuml 01-p2p-vs-client-server

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

title <b>Peer-to-Peer vs. Client–Server Architecture</b>\nSymmetric roles eliminate central points of failure

package "Client–Server Model" as CS {
  rectangle "Server" as srv <<server>>
  rectangle "Client A" as ca <<client>>
  rectangle "Client B" as cb <<client>>
  rectangle "Client C" as cc <<client>>

  ca -[$line_primary]-> srv : request
  srv -[$line_primary]-> ca : response
  cb -[$line_primary]-> srv : request
  srv -[$line_primary]-> cb : response
  cc -[$line_primary]-> srv : request
  srv -[$line_primary]-> cc : response
}

package "Peer-to-Peer Model" as P2P {
  rectangle "Peer 1" as p1 <<peer>>
  rectangle "Peer 2" as p2 <<peer>>
  rectangle "Peer 3" as p3 <<peer>>
  rectangle "Peer 4" as p4 <<peer>>

  p1 <-[$line_dynamic]-> p2
  p2 <-[$line_dynamic]-> p3
  p3 <-[$line_dynamic]-> p4
  p4 <-[$line_dynamic]-> p1
  p1 <-[$line_dynamic]-> p3
  p2 <-[$line_dynamic]-> p4
}

legend right
  |<$line_primary> <color:$line_neutral>  Server  </color>| Central service provider |
  |<$fill_primary>   Client  | Service consumer only |
  |<$line_dynamic> <color:$line_neutral>  Peer  </color>| Both provider and consumer |
end legend
@enduml
