# .github/workflows/build-latex.yml
#
# Builds all LaTeX documents and uploads PDFs as artifacts
# Triggered on push to main and pull requests

name: Build LaTeX Documents

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.tex'
      - '.github/workflows/build-latex.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.tex'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            texlive-pictures \
            latexmk
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Build all LaTeX documents
        run: |
          echo "Finding and building .tex files..."
          
          find src -name "*.tex" -type f | while read -r tex_file; do
            relative_path="${tex_file#src/}"
            output_dir="build/$(dirname "$relative_path")"
            filename=$(basename "$tex_file" .tex)
            
            mkdir -p "$output_dir"
            
            echo "Building: $relative_path"
            
            # Run pdflatex twice for cross-references
            cd "$(dirname "$tex_file")"
            pdflatex -interaction=nonstopmode -halt-on-error \
              -output-directory="$GITHUB_WORKSPACE/$output_dir" \
              "$(basename "$tex_file")" > /dev/null 2>&1 || true
            pdflatex -interaction=nonstopmode -halt-on-error \
              -output-directory="$GITHUB_WORKSPACE/$output_dir" \
              "$(basename "$tex_file")" > /dev/null 2>&1 || echo "::warning::Build issues in $relative_path"
            cd "$GITHUB_WORKSPACE"
          done
          
          # Count built PDFs
          pdf_count=$(find build -name "*.pdf" -type f | wc -l)
          echo "Built $pdf_count PDF files"
      
      - name: Clean up auxiliary files
        run: |
          find build -name "*.aux" -delete
          find build -name "*.log" -delete
          find build -name "*.out" -delete
          find build -name "*.toc" -delete
          find build -name "*.fls" -delete
          find build -name "*.fdb_latexmk" -delete
      
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdfs
          path: build/**/*.pdf
          retention-days: 30
          if-no-files-found: warn
      
      - name: Generate build summary
        run: |
          echo "## LaTeX Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Built PDFs" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          find build -name "*.pdf" -type f | sort | while read -r pdf; do
            echo "- \`${pdf#build/}\`" >> $GITHUB_STEP_SUMMARY
          done

  # Optional: Create a release with PDFs on tag
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: latex-pdfs
          path: pdfs
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: pdfs/**/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
