@startuml 06-ecommerce-example
!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

title E-Commerce System: Functional Decomposition

rectangle "**E-Commerce System**" as root $deep_dynamic {

  rectangle "**Storefront**" as sf $deep_primary {
    rectangle "Product\nCatalog" as sf1 $fill_primary
    rectangle "Shopping\nCart" as sf2 $fill_primary
    rectangle "Search" as sf3 $fill_primary
    rectangle "Recommen-\ndations" as sf4 $fill_primary
  }

  rectangle "**Order Management**" as om $deep_primary {
    rectangle "Order\nEntry" as om1 $fill_primary
    rectangle "Order\nFulfillment" as om2 $fill_primary
    rectangle "Order\nHistory" as om3 $fill_primary
    rectangle "Returns\nProcessing" as om4 $fill_primary
  }

  rectangle "**Inventory**" as inv $deep_primary {
    rectangle "Stock\nTracking" as inv1 $fill_primary
    rectangle "Warehouse\nMgmt" as inv2 $fill_primary
  }

  rectangle "**Customer\nManagement**" as cm $deep_primary {
    rectangle "Account\nProfiles" as cm1 $fill_primary
    rectangle "Authenti-\ncation" as cm2 $fill_primary
  }

  rectangle "**Payment**" as pay $deep_primary {
    rectangle "Transaction\nProcessing" as pay1 $fill_primary
    rectangle "Billing" as pay2 $fill_primary
  }

  rectangle "**Shipping**" as ship $deep_primary {
    rectangle "Delivery\nLogistics" as ship1 $fill_primary
    rectangle "Tracking" as ship2 $fill_primary
  }

}

legend right
  Decomposition criterion:
  **Business Capability**
  Each subsystem maps to a
  coherent business function.
end legend

@enduml
