@startuml

title Deployment View Relationships

!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

rectangle "Module Views\n\nCode organization\nPackages & layers\nBuild-time structure" as module $fill_ok

rectangle "C&C Views\n\nRuntime behavior\nComponents & connectors\nData/control flow" as cc $fill_primary

rectangle "Deployment Views\n\nPhysical mapping\nNodes & allocation\nInfrastructure topology" as deploy $fill_caution

rectangle "Operational Views\n\nMonitoring & alerts\nRunbooks & procedures\nCapacity planning" as ops $fill_alt

rectangle "IaC Specifications\n\nTerraform / CloudFormation\nKubernetes manifests\nAnsible playbooks" as iac $fill_invalid

module --> cc : implements\nbehavior
cc --> deploy : provides software\nelements
deploy --> ops : informs\noperations
deploy --> iac : generates\ninfrastructure code

note bottom of deploy
  Deployment views bridge logical design
  and physical infrastructure, connecting
  development concerns to operations
end note

@enduml
