@startuml

title Install Style Relations

!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

rectangle "Primary Relation: Allocated-To" as alloc $fill_ok {
    class "myapp.exe" as exe <<Software Element>>
    class "/opt/myapp/bin/" as bindir <<Directory>>
    
    exe -[$line_primary]-> bindir : <<allocated-to>>
}

note bottom of alloc
  Properties:
  - Installation timing (pre/during/post/runtime)
  - Conditionality (mandatory/optional/conditional)
  - Mutability (immutable/config-mutable/system-mutable)
  - Source (package/downloaded/generated)
end note

rectangle "Containment Relation" as contain $fill_caution {
    class "/opt/myapp/" as parent <<Directory>>
    class "/opt/myapp/bin/" as child1 <<Directory>>
    class "/opt/myapp/lib/" as child2 <<Directory>>
    class "/opt/myapp/etc/" as child3 <<Directory>>
    
    parent *-[$line_invalid]-> child1 : <<contains>>
    parent *-[$line_invalid]-> child2 : <<contains>>
    parent *-[$line_invalid]-> child3 : <<contains>>
}

rectangle "Depends-On Relation" as deps $fill_invalid {
    class "myapp.exe" as app <<Executable>>
    class "libcore.so" as lib <<Library>>
    class "libssl.so" as ssl <<System Library>>
    
    app -[$line_invalid]-> lib : <<depends-on>>\nload-time
    lib -[$line_invalid]-> ssl : <<depends-on>>\nruntime
}

note bottom of deps
  Dependency Types:
  - Build-time: needed to create
  - Install-time: needed during install
  - Load-time: needed when loading
  - Runtime: needed during execution
end note

rectangle "References Relation" as refs $fill_primary {
    class "app.conf" as conf <<Config>>
    class "/var/log/myapp/" as logpath <<Path>>
    class "https://api.example.com" as url <<URL>>
    
    conf -[$line_alt,dashed]-> logpath : <<references>>\nfile path
    conf -[$line_alt,dashed]-> url : <<references>>\nexternal URL
}

center footer Key Insight: Relations define installation ordering, validation requirements, and runtime dependencies
@enduml
