@startuml

!include ../../../../../../tooling/styles/plantuml/structural/deployment-diagram-style.iuml

title Install Style: Mapping Software to File Systems

rectangle "Software Architecture\n(C&C Components)" as arch $fill_primary {
    component "Application\nServer" as app
    component "Database\nConnector" as db
    component "Logging\nModule" as log
    component "Plugin\nSystem" as plugin
}

rectangle "File System Structure\n(Environmental Elements)" as fs $fill_ok {
    folder "/opt/myapp" as root {
        folder "bin/" as bin
        folder "lib/" as lib
        folder "etc/" as etc
        folder "var/" as var
        folder "plugins/" as plugins
    }
}

app -[$line_dynamic]-> bin : <<allocated-to>>\nexecutables
db -[$line_dynamic]-> lib : <<allocated-to>>\nlibraries
log -[$line_dynamic]-> var : <<allocated-to>>\nlog files
plugin -[$line_dynamic]-> plugins : <<allocated-to>>\nextensions

note bottom of arch
  Software Elements:
  Build artifacts derived from
  architectural components
end note

note bottom of fs
  Environmental Elements:
  Directory structure on
  target system
end note

center footer Key Concept: The install style documents how software artifacts map to file system locations
@enduml
