@startuml
!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

title Quality Attribute Impact of Layering\nHow the layered style affects key quality goals

rectangle "**Layered\nArchitecture**" as CENTER $fill_neutral

rectangle "Modifiability [++]\nChanges localized to layers" as MOD $fill_ok
rectangle "Portability [++]\nPlatform code isolated" as PORT $fill_ok
rectangle "Testability [+]\nLayers tested independently" as TEST $fill_ok
rectangle "Reusability [+]\nLower layers reusable" as REUSE $fill_ok
rectangle "Security [+]\nTrust boundaries align" as SEC $fill_ok
rectangle "Performance [-]\nLayer crossings add overhead" as PERF $fill_invalid

CENTER -[$line_ok]-> MOD
CENTER -[$line_ok]-> PORT
CENTER -[$line_ok]-> TEST
CENTER -[$line_ok]-> REUSE
CENTER -[$line_ok]-> SEC
CENTER -[$line_invalid]-> PERF

legend right
  | Symbol | Impact |
  | [++] | Strongly positive |
  | [+] | Positive |
  | [-] | Potential concern |
end legend
@enduml
