@startuml

title Common Publish-Subscribe Patterns\nFan-out, fan-in, and consumer groups for scalable event processing

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

package "Fan-Out Pattern (One-to-Many)" {
    component "Publisher" as FOP $deep_primary
    component "Topic" as FOT $deep_caution
    component "Sub 1" as FOS1 $deep_ok
    component "Sub 2" as FOS2 $deep_ok
    component "Sub 3" as FOS3 $deep_ok
    
    FOP -right-> FOT
    FOT -right-> FOS1
    FOT -right-> FOS2
    FOT -right-> FOS3
}

package "Fan-In Pattern (Many-to-One)" {
    component "Pub A" as FIA $deep_primary
    component "Pub B" as FIB $deep_primary
    component "Pub C" as FIC $deep_primary
    component "Topic" as FIT $deep_caution
    component "Subscriber" as FIS $deep_ok
    
    FIA -right-> FIT
    FIB -right-> FIT
    FIC -right-> FIT
    FIT -right-> FIS
}

package "Consumer Groups (Load-Balanced)" {
    component "Publisher" as CGP $deep_primary
    component "Partitioned\nTopic" as CGT $deep_caution
    
    component "Instance 1" as CGS1 $deep_ok
    component "Instance 2" as CGS2 $deep_ok
    component "Instance 3" as CGS3 $deep_ok
    
    CGP -right-> CGT
    CGT -right-> CGS1
    CGT -right-> CGS2
    CGT -right-> CGS3
}

note bottom of CGT
  Each event goes to
  ONE instance only
end note

@enduml
