@startuml

title Event Delivery Models\nPush-based vs. pull-based event distribution

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

package "Push Delivery" {
    component "Publisher" as PP $deep_primary
    component "Event\nBroker" as PB $deep_caution
    component "Subscriber" as PS $deep_ok
    
    PP -right-> PB : publish
    PB -right-> PS : PUSH
}

note bottom of PB
  Connector initiates delivery
  Low latency, subscriber must be ready
end note

package "Pull Delivery" {
    component "Publisher" as LP $deep_primary
    component "Event\nBroker" as LB $deep_caution
    component "Subscriber" as LS $deep_ok
    
    LP -right-> LB : publish
    LS -left-> LB : POLL
    LB -right-> LS : deliver
}

note bottom of LB
  Subscriber requests events
  Handles varying consumer speeds
end note

package "Streaming Delivery" {
    component "Publisher" as SP $deep_primary
    component "Streaming\nBroker" as SB $deep_caution
    component "Subscriber" as SS $deep_ok
    
    SP -right-> SB : publish
    SB <-right-> SS : persistent\nconnection
}

note bottom of SB
  Continuous connection
  Efficient for high-frequency events
end note

@enduml
