@startuml

title Microservices Event Bus Example\nLoose coupling through domain events

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

component "Order\nService" as OS $deep_primary

package "Event Bus" {
    component "OrderPlaced" as OP $deep_caution
    component "PaymentReceived" as PR $deep_caution
    component "OrderShipped" as OSH $deep_caution
}

component "Inventory\nService" as IS $deep_ok
component "Payment\nService" as PS $deep_ok
component "Shipping\nService" as SS $deep_ok
component "Notification\nService" as NS $deep_ok

OS -down-> OP : publishes
PS -down-> PR : publishes
SS -down-> OSH : publishes

OP -down-> IS : subscribes
OP -down-> PS : subscribes
OP -down-> NS : subscribes

PR -down-> SS : subscribes
PR -down-> NS : subscribes

OSH -down-> NS : subscribes

note bottom of NS
  Services react to events
  without direct coupling
  to event producers
end note

@enduml
