@startuml 09-technology-mapping
!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

!define BLUE $line_primary
!define GREEN $line_ok
!define ORANGE $line_caution
!define PURPLE $line_alt
!define TEAL $line_dynamic
!define RED $line_invalid

title <size:18><b>Data Model Technology Mapping</b></size>\n<size:12>How logical model concepts map to different database technologies</size>

rectangle "**Logical Data Model**" as LDM $theme_surface_2 {
  rectangle "Entities" as ent $theme_surface
  rectangle "Attributes" as attr $theme_surface
  rectangle "Relationships" as rel $theme_surface
  rectangle "Constraints" as con $theme_surface
}

rectangle "**Relational DB**\n(PostgreSQL, MySQL)" as RDB $deep_primary {
  rectangle "Tables" as t1 $fill_primary
  rectangle "Columns" as t2 $fill_primary
  rectangle "Foreign Keys" as t3 $fill_primary
  rectangle "CHECK, UNIQUE" as t4 $fill_primary
}

rectangle "**Document DB**\n(MongoDB, Couchbase)" as DDB $deep_ok {
  rectangle "Documents" as d1 $fill_ok
  rectangle "Fields" as d2 $fill_ok
  rectangle "Embedded / $ref" as d3 $fill_ok
  rectangle "Schema validation" as d4 $fill_ok
}

rectangle "**Graph DB**\n(Neo4j, Neptune)" as GDB $deep_alt {
  rectangle "Nodes" as g1 $fill_alt
  rectangle "Properties" as g2 $fill_alt
  rectangle "Edges" as g3 $fill_alt
  rectangle "Property checks" as g4 $fill_alt
}

rectangle "**Key-Value Store**\n(Redis, DynamoDB)" as KVS $deep_caution {
  rectangle "Values (objects)" as k1 $fill_caution
  rectangle "Fields in value" as k2 $fill_caution
  rectangle "Key design" as k3 $fill_caution
  rectangle "App-level" as k4 $fill_caution
}

ent -[$line_primary]-> t1
ent -[$line_ok]-> d1
ent -[$line_alt]-> g1
ent -[$line_caution]-> k1

attr -[$line_primary]-> t2
attr -[$line_ok]-> d2
attr -[$line_alt]-> g2
attr -[$line_caution]-> k2

rel -[$line_primary]-> t3
rel -[$line_ok]-> d3
rel -[$line_alt]-> g3
rel -[$line_caution]-> k3

con -[$line_primary]-> t4
con -[$line_ok]-> d4
con -[$line_alt]-> g4
con -[$line_caution]-> k4

@enduml
