@startuml

!include ../../../../../../tooling/styles/plantuml/structural/package-diagram-style.iuml

title Aspect Solution: Modularized Crosscutting Concerns

together {
  package "<<aspect>> LoggingAspect" as la $fill_caution {
    rectangle "pointcut: service.*\nbefore + after advice" as la_d $fill_invalid
  }

  package "<<aspect>> SecurityAspect" as sa $fill_alt {
    rectangle "pointcut: @Secured\nbefore advice" as sa_d $deep_alt
  }

  package "<<aspect>> TransactionAspect" as ta $fill_ok {
    rectangle "pointcut: @Transactional\naround advice" as ta_d $fill_dynamic
  }
}

together {
  package "OrderService" as os $fill_primary {
    rectangle "Business Logic only" as os_bl $deep_primary
  }

  package "PaymentService" as ps $fill_primary {
    rectangle "Business Logic only" as ps_bl $deep_primary
  }

  package "InventoryService" as inv $fill_primary {
    rectangle "Business Logic only" as inv_bl $deep_primary
  }
}

la ..[$deep_caution]..> os : <<crosscuts>>
la ..[$deep_caution]..> ps : <<crosscuts>>
la ..[$deep_caution]..> inv : <<crosscuts>>

sa ..[$deep_invalid]..> os : <<crosscuts>>
sa ..[$deep_invalid]..> ps : <<crosscuts>>

ta ..[$deep_ok]..> os : <<crosscuts>>
ta ..[$deep_ok]..> ps : <<crosscuts>>
ta ..[$deep_ok]..> inv : <<crosscuts>>

note bottom of ps
  Base modules contain **only** business logic.
  Crosscutting concerns are modularized in aspects
  and applied via the **crosscuts** relation.
end note

@enduml
