@startuml

!include ../../../../../../tooling/styles/plantuml/structural/component-diagram-style.iuml

title The Crosscuts Relation (Many-to-Many)

together {
  class "<<aspect>>\nLogging" as log $fill_caution {
    pointcut: execution(* svc.*.*(..))
    advice: before, afterReturning
  }

  class "<<aspect>>\nSecurity" as sec $fill_invalid {
    pointcut: @Secured methods
    advice: before (authz check)
  }

  class "<<aspect>>\nTransaction" as tx $fill_ok {
    pointcut: @Transactional methods
    advice: around (begin/commit/rollback)
  }

  class "<<aspect>>\nCaching" as cache $fill_alt {
    pointcut: @Cacheable methods
    advice: around (cache lookup)
  }
}

together {
  class "OrderService" as os $fill_primary {
    + createOrder()  @Secured @Tx
    + getOrder()     @Cacheable
  }

  class "PaymentService" as pay $fill_primary {
    + processPayment()  @Secured @Tx
    + getBalance()      @Cacheable
  }

  class "InventoryService" as inv $fill_primary {
    + updateStock()   @Tx
    + checkStock()    @Cacheable
  }
}

log ..[$deep_caution]..> os : <<crosscuts>>
log ..[$deep_caution]..> pay : <<crosscuts>>
log ..[$deep_caution]..> inv : <<crosscuts>>

sec ..[$deep_invalid]..> os : <<crosscuts>>
sec ..[$deep_invalid]..> pay : <<crosscuts>>

tx ..[$deep_ok]..> os : <<crosscuts>>
tx ..[$deep_ok]..> pay : <<crosscuts>>
tx ..[$deep_ok]..> inv : <<crosscuts>>

cache ..[$deep_alt]..> os : <<crosscuts>>
cache ..[$deep_alt]..> pay : <<crosscuts>>
cache ..[$deep_alt]..> inv : <<crosscuts>>

note as N1
  One aspect crosscuts many modules.
  One module is crosscut by many aspects.
  Pointcuts define **which join points** are affected.
end note

@enduml
