@startuml
title Service Load Balancing Architecture - External Load Balancer

!include ../../../../../../tooling/styles/plantuml/structural/deployment-diagram-style.iuml

actor "Cloud Service\nConsumers" as CSC

cloud "Cloud Environment" as Cloud {

  rectangle "Load Balancer\n(external)" as LB

  package "Resource Pool of\nRedundant Cloud Service A Implementations" as Pool {

    package "Virtual Server A" as VSA {
      component "Cloud Service A" as CSA1
    }
    package "Virtual Server B" as VSB {
      component "Cloud Service A" as CSA2
    }
    package "Virtual Server C" as VSC {
      component "Cloud Service A" as CSA3
    }
  }

  package "Mechanisms" as Mechs {
    component "Cloud Usage Monitor" as CUM
    component "Resource Cluster\n(active-active)" as RC
    component "Resource Replication" as RR
  }
}

CSC --> LB : (1) requests
LB --> CSA1 : (2) horizontally\nscaled
LB --> CSA2 : (2) horizontally\nscaled
LB --> CSA3 : (2) horizontally\nscaled

CUM ..> Pool : monitor instances\nand IT resource use
RC ..> Pool : balance across\ncluster members
RR ..> Pool : generate cloud\nservice copies

note right of LB
  Specialized variation of the workload
  distribution architecture, geared to
  scaling cloud service implementations.
end note

@enduml
