@startuml
title Service Load Balancing Architecture - Built-in Load Balancer

!include ../../../../../../tooling/styles/plantuml/interaction/sequence-diagram-style.iuml

actor "Cloud Service\nConsumers" as CSC

cloud "Cloud Environment" as Cloud {

  package "Virtual Server A (primary)" as VSA {
    component "Cloud Service A\n+ load balancing logic" as CSA1
  }
  package "Virtual Server B" as VSB {
    component "Cloud Service A" as CSA2
  }
  package "Virtual Server C" as VSC {
    component "Cloud Service A" as CSA3
  }
}

CSC --> CSA1 : (1) requests
CSA1 --> CSA2 : (2) distribute to\nneighboring server
CSA1 --> CSA3 : (2) distribute to\nneighboring server

note right of CSA1
  Primary server contains built-in
  load balancing logic and communicates
  with neighboring servers to balance
  the workload.
end note

@enduml

