# .github/actions/build-documents/action.yml
# Reusable composite action for building LaTeX documents
name: 'Build LaTeX Documents'
description: 'Build LaTeX documents with caching and selective compilation'

inputs:
  source-dir:
    description: 'Root directory containing .tex files'
    required: false
    default: 'src'
  document-filter:
    description: 'Glob pattern to filter documents (e.g., "src/security/**/*.tex")'
    required: false
    default: ''
  changed-files:
    description: 'Newline-separated list of changed files (for selective builds)'
    required: false
    default: ''
  build-all:
    description: 'Force build of all documents regardless of changes'
    required: false
    default: 'false'
  cache-aux-files:
    description: 'Cache LaTeX auxiliary files between runs'
    required: false
    default: 'true'
  output-dir:
    description: 'Directory to copy built PDFs (empty = leave in place)'
    required: false
    default: ''

outputs:
  pdf-count:
    description: 'Number of PDFs built'
    value: ${{ steps.build.outputs.count }}
  pdf-files:
    description: 'JSON array of built PDF paths'
    value: ${{ steps.build.outputs.files }}
  failed-count:
    description: 'Number of failed builds'
    value: ${{ steps.build.outputs.failed }}

runs:
  using: 'composite'
  steps:
    - name: Verify build prerequisites
      shell: bash
      run: |
        # Verify pygments is available for minted
        if ! command -v pygmentize &> /dev/null; then
          echo "::error::pygmentize not found - minted package will fail"
          exit 1
        fi
        echo "✓ pygmentize: $(which pygmentize)"
        
        # Verify latexmk
        if ! command -v latexmk &> /dev/null; then
          echo "::error::latexmk not found"
          exit 1
        fi
        echo "✓ latexmk: $(which latexmk)"

    - name: Cache LaTeX auxiliary files
      if: inputs.cache-aux-files == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.source-dir }}/**/*.aux
          ${{ inputs.source-dir }}/**/*.fdb_latexmk
          ${{ inputs.source-dir }}/**/*.fls
          ${{ inputs.source-dir }}/**/*.toc
          ${{ inputs.source-dir }}/**/*.out
          ${{ inputs.source-dir }}/**/*.bbl
          ${{ inputs.source-dir }}/**/*.bcf
          ${{ inputs.source-dir }}/**/*.run.xml
          ${{ inputs.source-dir }}/**/_minted-*
        key: latex-aux-${{ inputs.document-filter || 'all' }}-${{ hashFiles(format('{0}/**/*.tex', inputs.source-dir)) }}
        restore-keys: |
          latex-aux-${{ inputs.document-filter || 'all' }}-
          latex-aux-

    - name: Discover documents to build
      id: discover
      shell: bash
      run: |
        set -euo pipefail
        
        SOURCE_DIR="${{ inputs.source-dir }}"
        FILTER="${{ inputs.document-filter }}"
        BUILD_ALL="${{ inputs.build-all }}"
        CHANGED_FILES="${{ inputs.changed-files }}"
        
        echo "::group::Document Discovery"
        
        # Find all root documents (files with \documentclass)
        if [[ -n "$FILTER" ]]; then
          # Use the filter pattern directly with find + grep
          filter_dir="${FILTER%%/**}"
          mapfile -t ALL_ROOTS < <(find "$filter_dir" -name '*.tex' -type f -exec grep -l '^\s*\\documentclass' {} \; 2>/dev/null || true)
        else
          mapfile -t ALL_ROOTS < <(find "$SOURCE_DIR" -name '*.tex' -type f -exec grep -l '^\s*\\documentclass' {} \; 2>/dev/null || true)
        fi
        
        echo "Total document roots found: ${#ALL_ROOTS[@]}"
        
        # Determine which documents to build
        if [[ "$BUILD_ALL" == "true" || -z "$CHANGED_FILES" ]]; then
          DOCS_TO_BUILD=("${ALL_ROOTS[@]}")
        else
          DOCS_TO_BUILD=()
          for root in "${ALL_ROOTS[@]}"; do
            root_dir="$(dirname "$root")"
            
            # Check if the root file itself changed
            if echo "$CHANGED_FILES" | grep -qF "$root"; then
              DOCS_TO_BUILD+=("$root")
              continue
            fi
            
            # Check if any file in the same directory changed
            if echo "$CHANGED_FILES" | grep -qF "$root_dir/"; then
              DOCS_TO_BUILD+=("$root")
              continue
            fi
            
            # Check if common/tooling changed
            if echo "$CHANGED_FILES" | grep -qE "(common|tooling)/.*\.tex$"; then
              DOCS_TO_BUILD+=("$root")
              continue
            fi
          done
        fi
        
        echo "Documents to build: ${#DOCS_TO_BUILD[@]}"
        echo "::endgroup::"
        
        # Output as newline-separated list
        printf 'roots<<EOF\n%s\nEOF\n' "$(printf '%s\n' "${DOCS_TO_BUILD[@]}")" >> "$GITHUB_OUTPUT"
        echo "count=${#DOCS_TO_BUILD[@]}" >> "$GITHUB_OUTPUT"

    - name: Build documents
      id: build
      shell: bash
      run: |
        set -euo pipefail
        
        ROOTS="${{ steps.discover.outputs.roots }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        
        if [[ -z "$ROOTS" ]]; then
          echo "No documents to build"
          echo "count=0" >> "$GITHUB_OUTPUT"
          echo "failed=0" >> "$GITHUB_OUTPUT"
          echo 'files=[]' >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        # Ensure pygmentize is in PATH
        export PATH="$PATH:/usr/bin"
        
        built_pdfs=()
        failed=0
        failed_files=()
        
        # Process each document
        while IFS= read -r tex_file; do
          [[ -z "$tex_file" ]] && continue
          
          dir="$(dirname "$tex_file")"
          base="$(basename "$tex_file")"
          name="${base%.tex}"
          pdf_name="${name}.pdf"
          
          echo ""
          echo "================================================================"
          echo "Building: $tex_file"
          echo "================================================================"
          
          # Create minted cache directory
          mkdir -p "${dir}/_minted-${name}"
          
          # Build with latexmk
          # -cd changes to directory (required for \input paths)
          # -pdf uses pdflatex (most compatible)
          # -shell-escape required for minted
          if latexmk -cd -pdf \
               -interaction=nonstopmode \
               -halt-on-error \
               -file-line-error \
               -shell-escape \
               "$tex_file" 2>&1 | tail -50; then
            
            pdf_path="${dir}/${pdf_name}"
            if [[ -f "$pdf_path" ]]; then
              echo "✓ SUCCESS: ${pdf_path}"
              built_pdfs+=("$pdf_path")
              
              # Copy to output directory if specified
              if [[ -n "$OUTPUT_DIR" ]]; then
                # Preserve directory structure relative to src/
                rel_path="${pdf_path#src/}"
                dest_dir="${OUTPUT_DIR}/$(dirname "$rel_path")"
                mkdir -p "$dest_dir"
                cp "$pdf_path" "$dest_dir/"
                echo "  → Copied to: ${dest_dir}/${pdf_name}"
              fi
            else
              echo "⚠ WARNING: Build completed but PDF not found at ${pdf_path}"
            fi
          else
            echo "✗ FAILED: $tex_file"
            failed_files+=("$tex_file")
            ((failed++)) || true
          fi
        done <<< "$ROOTS"
        
        echo ""
        echo "================================================================"
        echo "BUILD SUMMARY"
        echo "================================================================"
        echo "Successful: ${#built_pdfs[@]}"
        echo "Failed: $failed"
        
        if [[ $failed -gt 0 ]]; then
          echo ""
          echo "Failed files:"
          for f in "${failed_files[@]}"; do
            echo "  - $f"
          done
        fi
        
        # Set outputs
        echo "count=${#built_pdfs[@]}" >> "$GITHUB_OUTPUT"
        echo "failed=$failed" >> "$GITHUB_OUTPUT"
        
        if [[ ${#built_pdfs[@]} -gt 0 ]]; then
          printf 'files=%s\n' "$(printf '%s\n' "${built_pdfs[@]}" | jq -R . | jq -sc .)" >> "$GITHUB_OUTPUT"
        else
          echo 'files=[]' >> "$GITHUB_OUTPUT"
        fi
        
        # Fail if ALL builds failed
        if [[ $failed -gt 0 && ${#built_pdfs[@]} -eq 0 ]]; then
          echo "::error::All document builds failed!"
          exit 1
        fi
