@startuml

!include ../../../../../../tooling/styles/plantuml/interaction/sequence-diagram-style.iuml

title Request/Reply Interaction Model

participant "Client" as C $fill_primary
participant "Connector" as CONN $fill_caution
participant "Server" as S $fill_ok

autonumber

== Synchronous Request/Reply ==

C -> C : Construct request
activate C $fill_primary

C -> CONN : Send request
activate CONN $fill_caution

CONN -> S : Transmit
activate S $fill_ok

S -> S : Parse request
S -> S : Execute operation
S -> S : Construct reply

S -> CONN : Send reply
deactivate S

CONN -> C : Return reply
deactivate CONN

C -> C : Process reply
deactivate C

note right of C
  Client blocks until
  reply is received
end note

== Asynchronous Variant ==

C -> C : Construct request
activate C $fill_primary

C -> CONN : Send request (async)
activate CONN $fill_caution

C -> C : Continue execution
note right of C : Non-blocking

CONN -> S : Transmit
activate S $fill_ok
S -> S : Process
S -> CONN : Reply
deactivate S

CONN --> C : Callback/Future
deactivate CONN
deactivate C
@enduml
