# .github/actions/setup-latex/action.yml
# Reusable composite action for setting up LaTeX environment with caching
name: 'Setup LaTeX Environment'
description: 'Install TeX Live with intelligent caching for fast builds'

inputs:
  cache-key-prefix:
    description: 'Prefix for cache key (allows cache busting)'
    required: false
    default: 'texlive-v2'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache-texlive.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Cache TeX Live packages
      id: cache-texlive
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/texlive
          ~/.texlive
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-texlive
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-texlive

    - name: Install TeX Live and Pygments
      shell: bash
      run: |
        # Always install pygments (it's small and critical for minted)
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3-pygments
        
        # Verify pygmentize is available
        which pygmentize || { echo "ERROR: pygmentize not found"; exit 1; }
        pygmentize -V
        
        # Install TeX Live if not cached
        if [[ "${{ steps.cache-texlive.outputs.cache-hit }}" != "true" ]]; then
          echo "Installing TeX Live packages..."
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-pictures \
            texlive-science \
            texlive-bibtex-extra \
            texlive-luatex \
            latexmk \
            biber \
            ghostscript \
            imagemagick
        fi
        
        sudo rm -rf /var/lib/apt/lists/* || true

    - name: Verify LaTeX installation
      shell: bash
      run: |
        echo "=== LaTeX Environment ==="
        echo "LuaLaTeX version:"
        lualatex --version | head -3
        echo ""
        echo "latexmk version:"
        latexmk --version | head -1
        echo ""
        echo "Pygments version:"
        pygmentize -V
        echo ""
        echo "Pygmentize location:"
        which pygmentize
