# .github/actions/setup-latex/action.yml
# Reusable composite action for setting up LaTeX environment with caching
name: 'Setup LaTeX Environment'
description: 'Install TeX Live with intelligent caching for fast builds'

inputs:
  cache-key-prefix:
    description: 'Prefix for cache key (allows cache busting)'
    required: false
    default: 'texlive-v3'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache-texlive.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Cache TeX Live installation
      id: cache-texlive
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/texlive
          ~/.texlive*
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-full
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: Install TeX Live and dependencies
      shell: bash
      run: |
        set -euo pipefail
        
        echo "::group::Installing system dependencies"
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          python3-pygments \
          ghostscript \
          imagemagick
        echo "::endgroup::"
        
        # Install TeX Live if not cached
        if [[ "${{ steps.cache-texlive.outputs.cache-hit }}" != "true" ]]; then
          echo "::group::Installing TeX Live packages"
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-pictures \
            texlive-science \
            texlive-bibtex-extra \
            texlive-luatex \
            texlive-xetex \
            latexmk \
            biber
          echo "::endgroup::"
        else
          echo "TeX Live restored from cache"
        fi
        
        sudo rm -rf /var/lib/apt/lists/* || true

    - name: Verify LaTeX installation
      shell: bash
      run: |
        echo "=== LaTeX Environment Verification ==="
        echo "pdflatex: $(pdflatex --version | head -1)"
        echo "lualatex: $(lualatex --version | head -1)"
        echo "latexmk:  $(latexmk --version | head -1)"
        echo "pygmentize: $(pygmentize -V)"
        echo "pygmentize path: $(which pygmentize)"
        
        # Ensure pygmentize is in a standard location for minted
        if [[ ! -f /usr/bin/pygmentize ]]; then
          sudo ln -sf "$(which pygmentize)" /usr/bin/pygmentize 2>/dev/null || true
        fi
