# .github/actions/setup-latex/action.yml
# Reusable composite action for setting up LaTeX environment
name: 'Setup LaTeX Environment'
description: 'Install TeX Live for LaTeX document compilation'

inputs:
  extra-packages:
    description: 'Additional apt packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install TeX Live and dependencies
      shell: bash
      run: |
        set -euo pipefail
        
        echo "::group::Installing TeX Live packages"
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-pictures \
          texlive-science \
          texlive-bibtex-extra \
          texlive-luatex \
          texlive-xetex \
          latexmk \
          biber \
          python3-pygments \
          ghostscript \
          ${{ inputs.extra-packages }}
        echo "::endgroup::"
        
        sudo rm -rf /var/lib/apt/lists/* || true

    - name: Verify LaTeX installation
      shell: bash
      run: |
        echo "=== LaTeX Environment Verification ==="
        echo "pdflatex:   $(which pdflatex) - $(pdflatex --version | head -1)"
        echo "latexmk:    $(which latexmk) - $(latexmk --version | head -1)"
        echo "pygmentize: $(which pygmentize) - $(pygmentize -V)"
        
        # Ensure pygmentize is accessible for minted
        if [[ ! -f /usr/bin/pygmentize ]]; then
          sudo ln -sf "$(which pygmentize)" /usr/bin/pygmentize 2>/dev/null || true
        fi
